### ISSUE TITLE
META Portal improvements

### ISSUE THREAD

**Issue by moul** [gnolang/gno#1187]
Random ideas for improving the portal loop (#1108):

-  [ ] Include the block height in the footer.
-  [ ] Enhance error handling by displaying errors within the theme instead of causing panic.
-  [ ] Implement a maintenance mode for when the node is starting.
-  [ ] Create a page that lists the N latest contracts.
-  [ ] Add a form to allow the execution of arbitrary data for contracts using `q_exec`.
-  [ ] Show the contract publisher in the footer.
-  [ ] Display the date/height of the most recent state modification for the current realm.

**Comment by jefft0** [comment]
It seems that "Add a form to execute arbitrary data for contracts using q_exec" is completed by https://github.com/gnolang/gno/pull/4858 .

**Comment by jefft0** [comment]
It seems that "Improve the help generation based on @thehowl's work with gno doc" is completed by https://github.com/gnolang/gno/pull/3851 and following PRs which show function docs, function signatures with types, distinguish non-crossing functions, etc

**Comment by jefft0** [comment]
Linked issue [include the block height in the footer](https://github.com/gnolang/gno/issues/1214) was closed by the Stalebot. Should it be re-opened?

**Comment by jefft0** [comment]
For "Display the date/height of the most recent state modification for the current realm", @thehowl says "Would need to complicate the VM. Defer for now."
