### ISSUE TITLE
META 'maketx run' improvements

### ISSUE THREAD

**Issue by moul** [gnolang/gno#1283]
Continues #1001.

-  [ ] Perform most checks locally before initiating the actual transaction. This depends on auto-fetching missing imports and can possibly be achieved by combining `gno run --quiet ./scripts.gno && gnokey maketx run`, potentially using a `misc/gno-run` bash script for convenience.
-  [ ] Remove comments for gas optimization (except if `--no-optimize` is specified)
-  [ ] Remove unused imports for gas optimization (except if `--no-optimize` is specified)
-  [ ] `gnokey maketx run --watch ./path/to/script.gno` to unlock the private key only once?
-  [ ] `gnokey maketx run | gnorender` -> markdown
