### ISSUE TITLE
META - Review Team

### ISSUE THREAD

**Issue by thehowl** [gnolang/gno#2890]
- [x] Automed label to highlight non-core PRs (using actions/labeler?) #3072 
- [ ] Updates to contributing, to set up guidelines - continuing #2477. #3073

**Comment by Kouteki** [comment]
Notes
- The review team should focus on PRs only, they are currently a bottleneck.
- The review team should focus on contributor PRs, and ignore PRs made by the core team. Over time, and as contributors get more familiar with the project, we'll revisit this decision.
- Failing CI is a valid reason to reject a PR.
- Guideline content: if a PR is intentionally failing CI, the guideline should state that the author needs to state that it's intentional.
- Guideline content: PRs should reference the issues they are addressing
- Guideline content: dependabot PR guidelines
- The review team should feel free to review PRs from their teams (i.e. be the 1st review). The 2nd review should be the core team.

Action items
- [x] @Kouteki to tag all issues that the review team should look at
- [x] @Kouteki to notify the review team once the labels are added, so they could start reviewing
- [x] @Kouteki to research possible improvements to the New issue templates

**Comment by jefft0** [comment]
Guideline content: When a review team member chooses a PR to review, they should add a comment with the `:eyes:` :eyes: emoji.

**Comment by jefft0** [comment]
[A related issue](https://github.com/gnolang/gno/issues/1466) uses the term "facilitators", which I like. We are using the label "review team" which is confusing. (One contributor thought that removing the "review team" label means that the PR won't be reviewed.) Can we rename the "review team" label to "facilitators"?

**Comment by jefft0** [comment]
We need a way for the PR to identify the states that it can be in. (All of these assume a PR created by a non-core dev.)
1. New PR: Add ~~"review team"~~ "facilitators" label
2. PR gets a comment or review by a core dev during initial review: Remove the ~~"review team"~~ "facilitators" label, add an explaining comment
3. The review team is finished with the initial review, ready for core devs: **What label to use?**

**Comment by Kouteki** [comment]
Notes from the Oct 17 meeting:

- The review team's goal shouldn't be to address the huge PR backlog; that's on the core team. Instead, they should help us with the top of the funnel, i.e. new PRs from external contributors that will only increase in volume over time.
- Right now we have multiple PRs trying to tackle the review flow: https://github.com/gnolang/gno/issues/1445 https://github.com/gnolang/gno/issues/1007 https://github.com/gnolang/gno/pull/1660
- We'll add the PR review flow on the core team agenda next week
- In the short term, I've changed the label 'review team' to 'review/triage-pending' and updated the label description
- Once we have a bot up, we'll automate the flow so that the review team can be assigned automatically on external PRs
- Our best idea right now is to get rid off CODEOWNERS, don't assign anyone automatically.
- We'll use the Signal chat for internal coordination, and this meta issue for note keeping and planning.

**Comment by Kouteki** [comment]
Optimum review flow
- Pick a PR with 'review/triage-pending'
- Assign yourself & review a PR
- Approve or request changes
- Remove the 'review/triage-pending' label

**Comment by Kouteki** [comment]
A couple of updates:
- https://github.com/gnolang/gno/pull/3022 merged
- Dependabot should be treated as an external contributor. Review Dependabot PRs if you feel comfortable, they will be tagged for this team.

**Comment by thehowl** [comment]
Closing as this issue is not being updated.
