### ISSUE TITLE
[META] r/boards"2"

### ISSUE THREAD

**Issue by salmad3** [gnolang/gno#3137]
## Context:

> [!warning]
> Criteria is TBD and subject to change

"boards" serves as a demo and potential reference implementation for social media-like boards with posts and interactions. The goal is to fully develop this implementation and use it as the foundation for a social interaction dApp on gno.land. For mainnet, "boards" will provide immediate functionality and connect users from day one to drive user enablement and acquisition. "boards" is also an opportunity to test Gno and gno.land as both a dogfooding exercise and a stress test to strengthen the chain's elements.

This META issue maps out the development plan for boards2, including creation, management, moderation, governance, and forking.

**To-Do**
- Forking criteria
- AdminDAO implementation with proposal system
- Alignment of AdminDAO with existing DAO implementations (e.g., GovDAO)
- ...

> [!Important]
> Current conceptual model:
> - Board creation and management are controlled by a flexible permissions system.
> - An `AdminDAO` oversees sensitive operations like board creation and renaming.
> - The system supports multiple roles: owners, admins, and moderators, each with distinct permission levels.
> - A flagging system is implemented for content moderation with configurable thresholds.
> - Forking is allowed at the board level, with clear guidelines for managing duplicate content.
> - The implementation allows for future policy changes without significant code restructuring.
> - Boards can have configurable default visibility settings for posts.
> - Spam prevention measures are in place to maintain board quality.

### System Relationships:

```mermaid
classDiagram
    class Board {
         <<realm>>
        +String name
        +Permissions permissions
        +UserDirectory userDirectory
        +Thread[] threads
    }

    class Thread {
         <<struct>>
        +String id
        +String title
        +Address author
        +Post[] posts
        +Flag[] flags
        +bool isLocked
    }

    class Post {
         <<struct>>
        +String id
        +String content
        +Address author
        +DateTime timestamp
        +Flag[] flags
    }

    class Flag {
         <<struct>>
        +Address user
        +String action
        +String reason
    }

    class Permissions {
        <<interface>>
        +WithPermission(user, action, args)
        +HasPermission(user, action, args)
        +GetRoles()
        +GetUsers(role)
    }

    class DefaultPermissions {
        +AdminDAO adminDAO
        +Map~Address, bool~ memberSet
    }

    class AdminDAO {
         <<realm>>
        +AdminDAO parent
        +Address[] admins
        +int threshold
        +ReviewProposal()
    }

    class UserDirectory {
        <<interface>>
        +Lookup(addr)
    }

    class UsersRealm {
         <<realm>>
        +LookupUser(name)
        +ValidateName(name)
    }

    %% Relationships
    Permissions <|.. DefaultPermissions : implements
    Board *-- Thread : contains
    Thread *-- Post : contains
    Post *-- Flag : has
    Thread *-- Flag : has
    Board *-- UserDirectory : has
    Board *-- Permissions : has
    DefaultPermissions --> AdminDAO : uses
    UserDirectory --> UsersRealm : interacts with
```

### Control Flow:

```mermaid
sequenceDiagram
    participant User
    participant Board
    participant Permissions
    participant AdminDAO
    participant UsersRealm

    User->>Board: Request Action (create/rename/fork)
    Board->>Permissions: WithPermission(user, action, args)
    alt Permission Denied
        Permissions-->>Board: Deny Action
        Board-->>User: Action Denied Message
    else Requires AdminDAO Approval
        Permissions->>Permissions: Check basic rules
        Permissions->>UsersRealm: Validate Name (if needed)
        UsersRealm-->>Permissions: Validation Result
        Permissions->>AdminDAO: Create Proposal
        Note over AdminDAO: Review Process
        AdminDAO-->>Permissions: Approve/Reject
        alt Approved
            Permissions-->>Board: Execute Action
            Board-->>User: Action Successful
        else Rejected
            Permissions-->>Board: Deny Action
            Board-->>User: Action Denied Message
        end
    end
```

### Dependency Hierarchy:

```mermaid
graph TD
    A[AdminDAO] -->|Enables| B[Board Creation]
    A -->|Enables| C[Board Forking]
    A -->|Enables| D[Board Renaming]

    E[Permissions] -->|Enforces| F[Access Control]
    E -->|Manages| G[Role-based Permissions]
    E -->|Validates| H[Name Rules]

    I[Board] -->|Uses| E
    I -->|Has| J[UserDirectory]
    I -->|Contains| K[Posts]

    K -->|Has| L[Flags]

    M[DefaultPermissions] -->|Uses| A
    M -->|Implements| E

    N[users Realm] -->|Interacts with| J
    N -->|Validates| H
```

### Creation & Management:

Includes:
- [ ] A `CreateBoard()` function that uses the permissions system and AdminDAO interaction to control board creation.
- [ ] A board renaming process that requires owner initiation and AdminDAO approval.
- [ ] A `DeleteBoard()` function that allows owners to delete a board, subject to permissions and AdminDAO approval.
- [ ] Basic board operations (e.g., post creation, deletion) that utilize the permissions system.
- [ ] Functions to manage board settings, such as default visibility of posts and whether the board is open or invite-only.
- [ ] Name validation to prevent conflicts with existing usernames in the users realm (may be deferred).

### Permissions:

Includes:
- [ ] A flexible `Permissions` interface with methods like `WithPermission(user, action, args)` and `HasPermission(user, action, args)`.
- [ ] A role-based access control system supporting owners, admins, moderators, and members.
- [ ] Permissions associated with each role:
  - **Owners**: Can manage all aspects of a board, including other owners and admins; can rename and delete the board (subject to AdminDAO approval).
  - **Admins**: Can perform most actions except managing other admins or owners; cannot delete the board.
  - **Moderators**: Can manage content and users, such as hiding or deleting posts.
  - **Members**: Can create posts and comments, subject to board settings.
- [ ] Ability for owners to remove themselves, with safeguards ensuring the presence of at least one owner.
- [ ] Automatic membership assignment to owners, admins, and moderators within the board they oversee.
- [ ] An interface supporting role management, including functions to get roles and users associated with roles.

### Moderation:

Includes:
- [ ] A flagging system for content moderation to allow moderators to flag posts.
- [ ] Functions for moderators to hide or delete posts based on board settings.
- [ ] Configurable thresholds for actions, such as the number of flags required to delete a post (initially, a single moderator can delete a post).
- [ ] Locking of threads to allows owners or moderators to lock a thread to prevent further comments.
- [ ] Spam prevention measures to maintain board quality.

### Forking:

Includes:
- [ ] A `ForkBoard()` function to create new boards based on existing ones.
- [ ] A system to track relationships between original boards and forks, possibly using data structures like linked lists.
- [ ] Visualization tools or data structure to represent fork relationships as interactive trees.
- [ ] Guidelines + mechanisms for managing duplicate content across forks.

### Considerations:

- Optimize gas consumption for frequent operations while maintaining security for sensitive actions.
- Ensure clear error handling with appropriate feedback mechanisms when permissions are denied.
- Design the permissions system flexibly to accommodate future governance models without major code rewrites.
- Implement callback mechanisms for asynchronous operations related to proposals in the AdminDAO.
- Address the challenges of upgrading realms and consider mechanisms for realm upgrades or migration.

## Current State of Related Components:

| Underlying Components            | Enables                                                           | Already in Gno?            | Implementation Required?       | In Progress? | Related Issues |
|--------------------------------|-------------------------------------------------------------------|----------------------------|-------------------------------|--------------|----------------|
| Copy-on-Write                  | Enables efficient data management without data duplication for forking        | No                         | Yes                           | Yes ([#3126](https://github.com/gnolang/gno/pull/3126)) | N/A |
| AVL Tree Structure             | Efficient management of ordered data like board names; quick lookups and uniqueness checks | Yes ([/demo/avl](https://github.com/gnolang/gno/tree/master/examples/gno.land/p/demo/avl)) | No                             | N/A          | N/A |
| Linked Lists                   | Manages sequences with frequent insertions/deletions, such as comment threads | No                         | Yes (custom implementation) | No           | N/A |
| Hash Maps (Maps)               | Enables fast lookups for user roles, permissions, and other mappings | Yes                    | No                             | N/A          | [#1374](https://github.com/gnolang/gno/issues/1374) (Proposal for ordered tree-structured maps) |
| Name Validation Functions      | Ensures uniqueness and correctness of board names and usernames   | No                         | Yes                           | No           | N/A |
| Binary Search Algorithms       | Fast retrieval of data in ordered collections                     | No                         | Yes                           | No           | N/A |
| Sorting Algorithms             | Ordering posts, comments, or boards based on criteria             | To update                           | To update                             | No           | N/A |
| Serialization Utilities        | Can be used for data storage and transmission                        | To update           | To update              | N/A          | N/A |
| Concurrency Primitives         | Ensures data consistency during concurrent access                 | To update         | To update              | N/A          | N/A |

**Comment by salmad3** [comment]
**[20-11-24]:**

Criteria continues to evolve.

- **Ownership and Roles**:
    - The concept of ownership is evolving, with discussions around making boards potentially ownerless or having DAOs as owners. This impacts the current definition where owners have extensive control, including removing other owners as initially proposed.
    - An `Owner` can be seen as a special `Admin` member with additional privileges, such as removing other admins. However, if owners remove themselves, the board can become autonomous, relying on admins to manage it.
    - The [`Permissions` interface](#3139) should be adaptable to support both individual and DAO-based ownership models. This includes ensuring that permission checks can handle scenarios where a DAO might assume roles traditionally held by individual users.
    - We'll need to consider redefining [roles](#3171) to accommodate the possibility of a board being governed by a DAO or having no traditional owner.

- **Governance**:
   - The use of proposals for certain actions is being debated. For example, while renaming a board might not require a proposal if done by an `Owner`, it would for an `Admin`. The system should allow flexibility in whether actions require proposals based on user roles.
   - The integration with AdminDAO needs to be more explicitly defined, especially considering future governance decisions that might involve chain-level control or proposals for board management1
   - The role of `AdminDAO` in approving upgrades or changes should be clarified, as current discussions suggest that governance might shift from admins to a more chain-centric model.
   - The process for upgrading boards or implementing new versions needs a clear governance path, potentially involving proposals that could be approved by a DAO or chain-level decision-making body.

- **Versioning**: 
  - Well, versioning applies broadly and is not limited to boards.
  - The process for upgrading boards may involve setting notification messages and potentially freezing activity on older versions to encourage migration to newer versions. This approach allows flexibility while maintaining user awareness of changes. In using a notification system, we can experiment with [push notifications](#3018).
  - A proxy system was proposed to manage different versions of contracts.

- **Moderation**
  - The idea of having a global `AdminDAO` that can oversee boards was discussed. This entity could freeze boards or inject `Moderators` in cases of inappropriate content or governance issues.
  - Still, there are challenges and general concerns about managing inappropriate content on boards.
  - However, handling persistent data, especially when dealing with inappropriate content, poses challenges due to immutability. Discussions included potential solutions like using snapshots or having special privileges for data deletion managed by the associated DAO.
