### ISSUE TITLE
[META] 🏗3️⃣ test3.gno.land

### ISSUE THREAD

**Issue by moul** [gnolang/gno#361]
Meta issue for https://github.com/gnolang/gno/milestone/3, to keep a place for discussions.

* [ ] if possible: new faucet system
  * [x] faucet contract (#246)
  * [ ] community bot (discord?) (#364)
  * [ ] archive old faucet code
  * [ ] EDIT: we'll maybe just launch test3 with the current faucet system + actual r/faucet, and make the discord bot in a few weeks, in case the actual faucet is drained.
* [x] create a realm for the official gnolang blog (#370)
* [ ] update homepage, off-chain doc, on-chain doc
* [ ] bonus: new version of independence-day airdrop (https://github.com/gnolang/independence-day/pull/16)
* [ ] bonus: namespace support + move existing realms to next locations (#336, #365, #375)

anything else?
